export const languages = {
  "en": {
    "aldb.actions.add_default_links": "Add Default Links",
    "aldb.actions.change": "Change ALDB Record",
    "aldb.actions.create": "Create ALDB Record",
    "aldb.actions.hide": "Hide Unused",
    "aldb.actions.manage": "All-Link Database",
    "aldb.actions.new": "New ALDB Record",
    "aldb.actions.show": "Show Unused",
    "aldb.caption": "All-Link Database",
    "aldb.fields.group": "Group",
    "aldb.fields.id": "Record ID",
    "aldb.fields.in_use": "In Use",
    "aldb.fields.mode": "Mode",
    "aldb.fields.modified": "Modified",
    "aldb.fields.target": "Tartet Address",
    "aldb.fields.target_device": "Target Device Name",
    "aldb.is_loading": "The All-Link Database is loading. This may take up to 20 minutes.",
    "aldb.mode.controller": "Controller",
    "aldb.mode.responder": "Responder",
    "aldb.no_data": "The All-Link Database has not been loaded. Please load from the device.",
    "aldb.status.caption": "ALDB Status",
    "aldb.status.empty": "Not loaded",
    "aldb.status.failed": "Failed to load",
    "aldb.status.loaded": "Loaded",
    "aldb.status.loading": "Loading",
    "aldb.status.partial": "Partially loaded",
    "aldb.status.undefined": "undefined",
    "common.actions.load": "Load from device",
    "common.actions.reset": "Undo changes",
    "common.actions.write": "Write to device",
    "common.error.address": "Invalid Insteon device address.",
    "common.error.base": "Please check your entries.",
    "common.error.device_not_found": "An Insteon device was not found.",
    "common.error.load": "The device did not respond as expected to the read request.",
    "common.error.write": "The device did not respond as expected to the write request.",
    "common.warn.add_default_links": "Changes will be made to this device and your modem.",
    "common.warn.load": "Reading from the device may take a while.",
    "common.warn.wake_up": "Because this is a battery operated device, the process will run in the background the next time the device wakes up.",
    "common.warn.write": "Writing changes to the device may will take a while.",
    "properties.actions.change": "Change Property Value",
    "properties.actions.manage": "Insteon Properties",
    "properties.caption": "Properties",
    "properties.descriptions.SOFTWARE_LOCK_ON": "Software lock on",
    "properties.descriptions.ambient_light_intensity": "Ambient light intensity",
    "properties.descriptions.app_retries": "App retries",
    "properties.descriptions.awake_interval": "Awake interval",
    "properties.descriptions.backlight": "Backlight",
    "properties.descriptions.battery_level": "Battery level",
    "properties.descriptions.battery_low_level": "Battery low level",
    "properties.descriptions.blink_on_error_off": "Blink on error off",
    "properties.descriptions.blink_on_error_on": "Blink on error on",
    "properties.descriptions.blink_on_tx_on": "Blink on tx on",
    "properties.descriptions.broadcast_number": "Broadcast number",
    "properties.descriptions.button": "Button",
    "properties.descriptions.button_lock_on": "Button lock on",
    "properties.descriptions.celsius": "Celsius",
    "properties.descriptions.change_delay": "Change delay",
    "properties.descriptions.checksum_off": "Checksum off",
    "properties.descriptions.cleanup_report_off": "Cleanup report off",
    "properties.descriptions.cleanup_report_on": "Cleanup report on",
    "properties.descriptions.config": "Config",
    "properties.descriptions.crc_error_count": "Crc error count",
    "properties.descriptions.database_delta": "Database delta",
    "properties.descriptions.delay": "Delay",
    "properties.descriptions.detach_load_on": "Detach load on",
    "properties.descriptions.dual_line_on": "Dual line on",
    "properties.descriptions.duration_high": "Duration high",
    "properties.descriptions.duration_low": "Duration low",
    "properties.descriptions.forward_on": "Forward on",
    "properties.descriptions.grouped_on": "Grouped on",
    "properties.descriptions.hardware_led_off": "Hardware led off",
    "properties.descriptions.hardware_light_sensitivity": "Hardware light sensitivity",
    "properties.descriptions.hardware_night_mode": "Hardware night mode",
    "properties.descriptions.hardware_send_on_only": "Hardware send on only",
    "properties.descriptions.hardware_timeout": "Hardware timeout",
    "properties.descriptions.heart_beat_off": "Heart beat off",
    "properties.descriptions.heart_beat_on": "Heart beat on",
    "properties.descriptions.heartbeat_interval": "Heartbeat interval",
    "properties.descriptions.humidity_high": "Humidity high set level",
    "properties.descriptions.humidity_low": "Humidity low set level",
    "properties.descriptions.humidity_offset": "Humidity offset",
    "properties.descriptions.ignore_jumper_on": "Ignore jumper on",
    "properties.descriptions.insteon_off": "Insteon off",
    "properties.descriptions.key_beep_on": "Key beep on",
    "properties.descriptions.latching_on": "Latching on",
    "properties.descriptions.led_brightness": "LED brightness",
    "properties.descriptions.led_dimming": "LED dimming",
    "properties.descriptions.led_off": "LED off",
    "properties.descriptions.led_on": "LED on",
    "properties.descriptions.light_sensitivity": "Light sensitivity",
    "properties.descriptions.link_to_ff_group": "Link to ff group",
    "properties.descriptions.listen_only_on": "Listen only on",
    "properties.descriptions.load_sense_2_on": "Load sense 2 on",
    "properties.descriptions.load_sense_on": "Load sense on",
    "properties.descriptions.lsb_of_sleep_interval": "LSB of sleep interval",
    "properties.descriptions.main": "Main",
    "properties.descriptions.master": "Master thermostat",
    "properties.descriptions.momentary_follow_sense": "Momentary follow sense",
    "properties.descriptions.momentary_line_on": "Momentary line on",
    "properties.descriptions.momentary_on": "Momentary on",
    "properties.descriptions.momentary_on_off_trigger": "Momentary on off trigger",
    "properties.descriptions.motion_timeout": "Motion timeout",
    "properties.descriptions.multi_send_on": "Multi send on",
    "properties.descriptions.night_mode_only": "Night mode only",
    "properties.descriptions.non_toggle_mask": "Non-toggle bit mask",
    "properties.descriptions.non_toggle_on_off_mask": "Non-toggle on/off bit mask",
    "properties.descriptions.not_3_way": "Not 3 way",
    "properties.descriptions.off_mask": "Off bit mask",
    "properties.descriptions.on_level": "On level",
    "properties.descriptions.on_mask": "On bit mask",
    "properties.descriptions.powerline_disable_on": "Powerline disable on",
    "properties.descriptions.prescaler": "Prescaler",
    "properties.descriptions.program_lock_on": "Program lock on",
    "properties.descriptions.radio_button_group": "Radio button group",
    "properties.descriptions.ramp_rate": "Dimmer ramp rate",
    "properties.descriptions.relay_on_sense_on": "Relay on sense on",
    "properties.descriptions.repeat_closed_on": "Repeat closed on",
    "properties.descriptions.repeat_open_on": "Repeat open on",
    "properties.descriptions.resume_dim_on": "Resume dim on",
    "properties.descriptions.reversed_on": "Reversed on",
    "properties.descriptions.rf_disable_on": "Rf disable on",
    "properties.descriptions.send_on_only_on": "Send on only on",
    "properties.descriptions.sense_sends_off": "Sense sends off",
    "properties.descriptions.sensor_status": "Sensor status",
    "properties.descriptions.signal_to_noise_failure_count": "Signal to noise failure count",
    "properties.descriptions.signal_to_noise_of_last_failure": "Signal to noise of last failure",
    "properties.descriptions.sleep_interval": "Sleep interval",
    "properties.descriptions.smart_hops_on": "Smart hops on",
    "properties.descriptions.software_support_on": "Software support on",
    "properties.descriptions.standard_holdoff": "Standard holdoff",
    "properties.descriptions.stay_awake_on": "Stay awake on",
    "properties.descriptions.temp_offset": "Temperature offset",
    "properties.descriptions.temp_offset_external": "Temperature offset external",
    "properties.descriptions.tend_on": "TEND on",
    "properties.descriptions.three_way_on": "Three way on",
    "properties.descriptions.time_24_hour_format": "Time 24 hour format",
    "properties.descriptions.toggle": "toggle mode",
    "properties.descriptions.trigger_group_mask": "Trigger group mask",
    "properties.descriptions.two_groups_on": "Two groups on",
    "properties.descriptions.x10_off": "X10 off",
    "properties.fields.description": "Description",
    "properties.fields.modified": "Modified",
    "properties.fields.name": "Property",
    "properties.fields.value": "Value",
    "properties.form_options.dimmable_light_main": "Main",
    "properties.form_options.non_toggle_off_mode": "Off only",
    "properties.form_options.non_toggle_on_mode": "On only",
    "properties.form_options.on_off_switch_b": "B",
    "properties.form_options.on_off_switch_c": "C",
    "properties.form_options.on_off_switch_d": "D",
    "properties.form_options.on_off_switch_e": "E",
    "properties.form_options.on_off_switch_f": "F",
    "properties.form_options.on_off_switch_g": "G",
    "properties.form_options.on_off_switch_h": "H",
    "properties.form_options.on_off_switch_main": "Main",
    "properties.form_options.toggle_on_off_mode": "On/Off",
    "properties.no_data": "No properties are available for this device.",
    "title": "Insteon"
  }
}